# PHP CircleCI 2.0 configuration file
# See: https://circleci.com/docs/2.0/language-php/
version: 2.1

workflows:
  main:
    jobs:
      - test-job:
          version: '7.4'

      - test-job:
          version: '8.0'

      - test-job:
          version: '8.1'
      
jobs:
  test-job:
    parameters:
      version:
        type: string

    docker:
      - image: cimg/php:<< parameters.version >> #circleci/php:8.1-node-browsers

    steps:
      - checkout

      - run: sudo apt update 
      - run: sudo apt install php-bcmath

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}-<< parameters.version >>
            - v1-dependencies-<< parameters.version >>

      - run: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}-<< parameters.version >>
          paths:
            - ./vendor

      - run: ./vendor/bin/phpunit
      - run: ./vendor/bin/psalm
